version: '3.7'
services:
  jenkins2:
    container_name: jenkins2
    restart: always
    build: ./master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:8080
      - 50000:50000